name: abc

dependencies:
  - python ={{ get_env("PY_VER", default="3.10") }}
  - cmake>=3.18
  - ninja
  - c-compiler
  - cxx-compiler
  - ccache   # [not win]
  - clcache  # [win]
  - make  # [unix]
  - readline=8.1  # [unix]
  - zlib
  - libpng
